### ISSUE TITLE
The Translucency doesn't work properly.

### ISSUE THREAD

**Issue by ElementalsTest** [LaughingQuoll/NoctisXI#19]
The bars that are meant to be translucent are translucent for about a second, and then become solid again. I'm using an iPhone SE, iOS 11.1.2 with Noctis XI v.1.0.2.

**Comment by Aransh** [comment]
Getting this too, it looks like if I open the settings app (for example), and slide down, the top bar is translucent, until I let go, and then it’s solid no matter how much I swipe. iPhone 7 plus 11.1.2

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.4

**Comment by Aransh** [comment]
@LaughingQuoll not fixed for me... now translucency doesn’t even work in the first place

**Comment by ElementalsTest** [comment]
@LaughingQuoll I wouldn’t call it fixed... Now there's no Translucency AT ALL!
