### ISSUE TITLE
Status bar not even (white/black)

### ISSUE THREAD

**Issue by dallasgroot** [LaughingQuoll/NoctisXI#2]
I’m an iPhone 8 user and have tested both stock statusbar which just displayed black along the entire top, and with LittleX installed, only the time was white and the rest was dark.
[Settings](https://imgur.com/a/URCre)

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.3

**Comment by ElementalsTest** [comment]
@LaughingQuoll Still broken for me on 1.0.4. iPhone SE, ios 11.1.2.
