### ISSUE TITLE
No pictures on messages app with 3D touch

### ISSUE THREAD

**Issue by messerffm** [LaughingQuoll/NoctisXI#36]
Instead of pictures of my contacts there are white circles if I’m using 3D Touch on my messages app.
Same issue with the tweak „Manila“ if you are using 3D Touch on Folders, just white spaces instead of app icons

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.4

**Comment by messerffm** [comment]
1.0.4 doesn’t fix it for me and there is 1.0.5 shown in cydia but if I install it, it shows 1.0.5 as an update again
